when:
  instance: ci.kokuwa.io
  repo: woodpecker/markdownlint
  event: [manual, push]
  branch: main
  path: [.woodpecker/dockerhub.yaml, README.md]

steps:

  metadata:
    image: kokuwaio/dockerhub-metadata
    settings:
      repository: kokuwaio/markdownlint
      description-short: A WoodpeckerCI plugin for markdownlint-cli to lint markdown files.
      categories: [developer-tools, integration-and-delivery]
      username: {from_secret: dockerhub_username}
      password: {from_secret: dockerhub_password}
