when:
  instance: ci.schnabel.org
  repo: kokuwaio/markdownlint
  event: push
  branch: main
  path: README.md

steps:

  metadata:
    image: kokuwaio/dockerhub-metadata
    settings:
      repository: kokuwaio/markdownlint
      description-short: A Woodpecker CI plugin for markdownlint-cli to lint markdown files.
      categories: [developer-tools, integration-and-delivery]
      username: {from_secret: DOCKERHUB_USERNAME}
      password: {from_secret: DOCKERHUB_PASSWORD}
